-- Rename all tables to snake_case to match education-service convention.
-- ALTER TABLE ... RENAME is atomic and preserves all data, indexes,
-- constraints and foreign keys (Postgres updates dependents by OID).
-- Prisma's auto-diff would emit DROP+CREATE and destroy 72,700 rows; this
-- migration is hand-written for that reason. Do not regenerate it.

ALTER TABLE "Language" RENAME TO language;
ALTER TABLE "GrammarCourse" RENAME TO grammar_course;
ALTER TABLE "GrammarLesson" RENAME TO grammar_lesson;
ALTER TABLE "PhoneticsCourse" RENAME TO phonetics_course;
ALTER TABLE "PhoneticsLesson" RENAME TO phonetics_lesson;
ALTER TABLE "SongsCourse" RENAME TO songs_course;
ALTER TABLE "SongsLesson" RENAME TO songs_lesson;
ALTER TABLE "SevenCourse" RENAME TO seven_course;
ALTER TABLE "SevenLesson" RENAME TO seven_lesson;
ALTER TABLE "SevenExercise" RENAME TO seven_exercise;
ALTER TABLE "Word" RENAME TO word;
ALTER TABLE "WordTheme" RENAME TO word_theme;
ALTER TABLE "WordThemeRelation" RENAME TO word_theme_relation;
ALTER TABLE "DrillTopic" RENAME TO drill_topic;
ALTER TABLE "DrillItem" RENAME TO drill_item;
ALTER TABLE "DrillItemRevision" RENAME TO drill_item_revision;
ALTER TABLE "CourseVocabulary" RENAME TO course_vocabulary;
ALTER TABLE "DrillSet" RENAME TO drill_set;
ALTER TABLE "DrillSetItem" RENAME TO drill_set_item;
ALTER TABLE "DrillSetRating" RENAME TO drill_set_rating;

-- Constraint and index names follow the tables to snake_case, so that
-- future 'migrate diff' runs report no drift. Generated by migrate diff
-- against a scratch DB with the table renames already applied; verified
-- to contain no DROP statements.

-- AlterTable
ALTER TABLE "course_vocabulary" RENAME CONSTRAINT "CourseVocabulary_pkey" TO "course_vocabulary_pkey";

-- AlterTable
ALTER TABLE "drill_item" RENAME CONSTRAINT "DrillItem_pkey" TO "drill_item_pkey";

-- AlterTable
ALTER TABLE "drill_item_revision" RENAME CONSTRAINT "DrillItemRevision_pkey" TO "drill_item_revision_pkey";

-- AlterTable
ALTER TABLE "drill_set" RENAME CONSTRAINT "DrillSet_pkey" TO "drill_set_pkey";

-- AlterTable
ALTER TABLE "drill_set_item" RENAME CONSTRAINT "DrillSetItem_pkey" TO "drill_set_item_pkey";

-- AlterTable
ALTER TABLE "drill_set_rating" RENAME CONSTRAINT "DrillSetRating_pkey" TO "drill_set_rating_pkey";

-- AlterTable
ALTER TABLE "drill_topic" RENAME CONSTRAINT "DrillTopic_pkey" TO "drill_topic_pkey";

-- AlterTable
ALTER TABLE "grammar_course" RENAME CONSTRAINT "GrammarCourse_pkey" TO "grammar_course_pkey";

-- AlterTable
ALTER TABLE "grammar_lesson" RENAME CONSTRAINT "GrammarLesson_pkey" TO "grammar_lesson_pkey";

-- AlterTable
ALTER TABLE "language" RENAME CONSTRAINT "Language_pkey" TO "language_pkey";

-- AlterTable
ALTER TABLE "phonetics_course" RENAME CONSTRAINT "PhoneticsCourse_pkey" TO "phonetics_course_pkey";

-- AlterTable
ALTER TABLE "phonetics_lesson" RENAME CONSTRAINT "PhoneticsLesson_pkey" TO "phonetics_lesson_pkey";

-- AlterTable
ALTER TABLE "seven_course" RENAME CONSTRAINT "SevenCourse_pkey" TO "seven_course_pkey";

-- AlterTable
ALTER TABLE "seven_exercise" RENAME CONSTRAINT "SevenExercise_pkey" TO "seven_exercise_pkey";

-- AlterTable
ALTER TABLE "seven_lesson" RENAME CONSTRAINT "SevenLesson_pkey" TO "seven_lesson_pkey";

-- AlterTable
ALTER TABLE "songs_course" RENAME CONSTRAINT "SongsCourse_pkey" TO "songs_course_pkey";

-- AlterTable
ALTER TABLE "songs_lesson" RENAME CONSTRAINT "SongsLesson_pkey" TO "songs_lesson_pkey";

-- AlterTable
ALTER TABLE "word" RENAME CONSTRAINT "Word_pkey" TO "word_pkey";

-- AlterTable
ALTER TABLE "word_theme" RENAME CONSTRAINT "WordTheme_pkey" TO "word_theme_pkey";

-- AlterTable
ALTER TABLE "word_theme_relation" RENAME CONSTRAINT "WordThemeRelation_pkey" TO "word_theme_relation_pkey";

-- RenameForeignKey
ALTER TABLE "course_vocabulary" RENAME CONSTRAINT "CourseVocabulary_languageId_fkey" TO "course_vocabulary_languageId_fkey";

-- RenameForeignKey
ALTER TABLE "drill_item" RENAME CONSTRAINT "DrillItem_languageId_fkey" TO "drill_item_languageId_fkey";

-- RenameForeignKey
ALTER TABLE "drill_item" RENAME CONSTRAINT "DrillItem_topicId_fkey" TO "drill_item_topicId_fkey";

-- RenameForeignKey
ALTER TABLE "drill_item_revision" RENAME CONSTRAINT "DrillItemRevision_itemId_fkey" TO "drill_item_revision_itemId_fkey";

-- RenameForeignKey
ALTER TABLE "drill_set" RENAME CONSTRAINT "DrillSet_languageId_fkey" TO "drill_set_languageId_fkey";

-- RenameForeignKey
ALTER TABLE "drill_set_item" RENAME CONSTRAINT "DrillSetItem_itemId_fkey" TO "drill_set_item_itemId_fkey";

-- RenameForeignKey
ALTER TABLE "drill_set_item" RENAME CONSTRAINT "DrillSetItem_setUuid_fkey" TO "drill_set_item_setUuid_fkey";

-- RenameForeignKey
ALTER TABLE "drill_set_rating" RENAME CONSTRAINT "DrillSetRating_setUuid_fkey" TO "drill_set_rating_setUuid_fkey";

-- RenameForeignKey
ALTER TABLE "drill_topic" RENAME CONSTRAINT "DrillTopic_languageId_fkey" TO "drill_topic_languageId_fkey";

-- RenameForeignKey
ALTER TABLE "grammar_course" RENAME CONSTRAINT "GrammarCourse_languageId_fkey" TO "grammar_course_languageId_fkey";

-- RenameForeignKey
ALTER TABLE "grammar_lesson" RENAME CONSTRAINT "GrammarLesson_courseId_fkey" TO "grammar_lesson_courseId_fkey";

-- RenameForeignKey
ALTER TABLE "phonetics_course" RENAME CONSTRAINT "PhoneticsCourse_languageId_fkey" TO "phonetics_course_languageId_fkey";

-- RenameForeignKey
ALTER TABLE "phonetics_lesson" RENAME CONSTRAINT "PhoneticsLesson_courseId_fkey" TO "phonetics_lesson_courseId_fkey";

-- RenameForeignKey
ALTER TABLE "seven_course" RENAME CONSTRAINT "SevenCourse_languageId_fkey" TO "seven_course_languageId_fkey";

-- RenameForeignKey
ALTER TABLE "seven_exercise" RENAME CONSTRAINT "SevenExercise_lessonId_fkey" TO "seven_exercise_lessonId_fkey";

-- RenameForeignKey
ALTER TABLE "seven_lesson" RENAME CONSTRAINT "SevenLesson_courseId_fkey" TO "seven_lesson_courseId_fkey";

-- RenameForeignKey
ALTER TABLE "songs_course" RENAME CONSTRAINT "SongsCourse_languageId_fkey" TO "songs_course_languageId_fkey";

-- RenameForeignKey
ALTER TABLE "songs_lesson" RENAME CONSTRAINT "SongsLesson_courseId_fkey" TO "songs_lesson_courseId_fkey";

-- RenameForeignKey
ALTER TABLE "word" RENAME CONSTRAINT "Word_languageId_fkey" TO "word_languageId_fkey";

-- RenameForeignKey
ALTER TABLE "word_theme_relation" RENAME CONSTRAINT "WordThemeRelation_themeId_fkey" TO "word_theme_relation_themeId_fkey";

-- RenameForeignKey
ALTER TABLE "word_theme_relation" RENAME CONSTRAINT "WordThemeRelation_wordId_fkey" TO "word_theme_relation_wordId_fkey";

-- RenameIndex
ALTER INDEX "CourseVocabulary_courseKey_languageId_lessonOrder_idx" RENAME TO "course_vocabulary_courseKey_languageId_lessonOrder_idx";

-- RenameIndex
ALTER INDEX "CourseVocabulary_courseKey_languageId_word_source_key" RENAME TO "course_vocabulary_courseKey_languageId_word_source_key";

-- RenameIndex
ALTER INDEX "DrillItem_courseKey_lessonOrder_idx" RENAME TO "drill_item_courseKey_lessonOrder_idx";

-- RenameIndex
ALTER INDEX "DrillItem_hash_key" RENAME TO "drill_item_hash_key";

-- RenameIndex
ALTER INDEX "DrillItem_languageId_materialLanguage_topicId_status_idx" RENAME TO "drill_item_languageId_materialLanguage_topicId_status_idx";

-- RenameIndex
ALTER INDEX "DrillItemRevision_itemId_createdAt_idx" RENAME TO "drill_item_revision_itemId_createdAt_idx";

-- RenameIndex
ALTER INDEX "DrillSet_courseKey_lessonOrder_idx" RENAME TO "drill_set_courseKey_lessonOrder_idx";

-- RenameIndex
ALTER INDEX "DrillSet_languageId_materialLanguage_reviewState_idx" RENAME TO "drill_set_languageId_materialLanguage_reviewState_idx";

-- RenameIndex
ALTER INDEX "DrillSet_popularityScore_idx" RENAME TO "drill_set_popularityScore_idx";

-- RenameIndex
ALTER INDEX "DrillSetItem_itemId_idx" RENAME TO "drill_set_item_itemId_idx";

-- RenameIndex
ALTER INDEX "DrillSetItem_setUuid_order_key" RENAME TO "drill_set_item_setUuid_order_key";

-- RenameIndex
ALTER INDEX "DrillSetRating_setUuid_raterType_raterId_key" RENAME TO "drill_set_rating_setUuid_raterType_raterId_key";

-- RenameIndex
ALTER INDEX "DrillTopic_languageId_materialLanguage_idx" RENAME TO "drill_topic_languageId_materialLanguage_idx";

-- RenameIndex
ALTER INDEX "DrillTopic_languageId_materialLanguage_slug_key" RENAME TO "drill_topic_languageId_materialLanguage_slug_key";

-- RenameIndex
ALTER INDEX "GrammarCourse_languageId_key" RENAME TO "grammar_course_languageId_key";

-- RenameIndex
ALTER INDEX "GrammarLesson_courseId_order_idx" RENAME TO "grammar_lesson_courseId_order_idx";

-- RenameIndex
ALTER INDEX "Language_code_key" RENAME TO "language_code_key";

-- RenameIndex
ALTER INDEX "Language_name_idx" RENAME TO "language_name_idx";

-- RenameIndex
ALTER INDEX "Language_order_idx" RENAME TO "language_order_idx";

-- RenameIndex
ALTER INDEX "PhoneticsCourse_languageId_key" RENAME TO "phonetics_course_languageId_key";

-- RenameIndex
ALTER INDEX "PhoneticsLesson_courseId_order_idx" RENAME TO "phonetics_lesson_courseId_order_idx";

-- RenameIndex
ALTER INDEX "SevenCourse_languageId_materialLanguage_key" RENAME TO "seven_course_languageId_materialLanguage_key";

-- RenameIndex
ALTER INDEX "SevenCourse_legacyId_key" RENAME TO "seven_course_legacyId_key";

-- RenameIndex
ALTER INDEX "SevenCourse_materialLanguage_idx" RENAME TO "seven_course_materialLanguage_idx";

-- RenameIndex
ALTER INDEX "SevenExercise_legacyKey_key" RENAME TO "seven_exercise_legacyKey_key";

-- RenameIndex
ALTER INDEX "SevenExercise_lessonId_order_idx" RENAME TO "seven_exercise_lessonId_order_idx";

-- RenameIndex
ALTER INDEX "SevenExercise_lessonId_order_key" RENAME TO "seven_exercise_lessonId_order_key";

-- RenameIndex
ALTER INDEX "SevenLesson_courseId_order_idx" RENAME TO "seven_lesson_courseId_order_idx";

-- RenameIndex
ALTER INDEX "SevenLesson_courseId_order_key" RENAME TO "seven_lesson_courseId_order_key";

-- RenameIndex
ALTER INDEX "SevenLesson_legacyId_key" RENAME TO "seven_lesson_legacyId_key";

-- RenameIndex
ALTER INDEX "SongsCourse_languageId_key" RENAME TO "songs_course_languageId_key";

-- RenameIndex
ALTER INDEX "SongsLesson_courseId_order_idx" RENAME TO "songs_lesson_courseId_order_idx";

-- RenameIndex
ALTER INDEX "Word_word_idx" RENAME TO "word_word_idx";

-- RenameIndex
ALTER INDEX "Word_word_languageId_translation_key" RENAME TO "word_word_languageId_translation_key";

-- RenameIndex
ALTER INDEX "WordTheme_name_idx" RENAME TO "word_theme_name_idx";

-- RenameIndex
ALTER INDEX "WordTheme_order_idx" RENAME TO "word_theme_order_idx";

-- RenameIndex
ALTER INDEX "WordThemeRelation_themeId_order_idx" RENAME TO "word_theme_relation_themeId_order_idx";

-- RenameIndex
ALTER INDEX "WordThemeRelation_wordId_themeId_order_key" RENAME TO "word_theme_relation_wordId_themeId_order_key";

