import { PrismaClient } from '@prisma/client';

/**
 * The grammar taxonomy the error analyzer is allowed to cluster into.
 *
 * Fixed, not runtime-editable: stable slugs are what make "which gaps does this student
 * keep failing" answerable across assignments and over time. Free-text clusters cannot be
 * compared to each other.
 *
 * Every language carries an `<lang>.other` row. The analyzer must always have a legal
 * target, so an unrecognised cluster lands there and is logged rather than dropped.
 */
export const GRAMMAR_TOPICS: Array<{
  slug: string;
  languageCode: string;
  titles: Record<string, string>;
  sortOrder: number;
}> = [
  { slug: 'en.prepositions-of-place', languageCode: 'en', sortOrder: 10,
    titles: { ru: 'Предлоги места', en: 'Prepositions of place' } },
  { slug: 'en.prepositions-of-movement', languageCode: 'en', sortOrder: 20,
    titles: { ru: 'Предлоги движения', en: 'Prepositions of movement' } },
  { slug: 'en.prepositions-of-time', languageCode: 'en', sortOrder: 30,
    titles: { ru: 'Предлоги времени', en: 'Prepositions of time' } },
  { slug: 'en.phrasal-prepositions', languageCode: 'en', sortOrder: 40,
    titles: { ru: 'Составные предлоги', en: 'Phrasal prepositions' } },
  { slug: 'en.articles', languageCode: 'en', sortOrder: 50,
    titles: { ru: 'Артикли', en: 'Articles' } },
  { slug: 'en.verb-tenses', languageCode: 'en', sortOrder: 60,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'en.irregular-verbs', languageCode: 'en', sortOrder: 70,
    titles: { ru: 'Неправильные глаголы', en: 'Irregular verbs' } },
  { slug: 'en.word-order', languageCode: 'en', sortOrder: 80,
    titles: { ru: 'Порядок слов', en: 'Word order' } },
  { slug: 'en.pronouns', languageCode: 'en', sortOrder: 90,
    titles: { ru: 'Местоимения', en: 'Pronouns' } },
  { slug: 'en.modal-verbs', languageCode: 'en', sortOrder: 100,
    titles: { ru: 'Модальные глаголы', en: 'Modal verbs' } },
  { slug: 'en.plurals-and-countability', languageCode: 'en', sortOrder: 110,
    titles: { ru: 'Множественное число и исчисляемость', en: 'Plurals and countability' } },
  { slug: 'en.spelling', languageCode: 'en', sortOrder: 120,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'en.vocabulary-choice', languageCode: 'en', sortOrder: 130,
    titles: { ru: 'Выбор слова', en: 'Vocabulary choice' } },
  { slug: 'en.other', languageCode: 'en', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'de.prepositions-with-cases', languageCode: 'de', sortOrder: 10,
    titles: { ru: 'Предлоги и падежи', en: 'Prepositions and cases' } },
  { slug: 'de.articles-and-gender', languageCode: 'de', sortOrder: 20,
    titles: { ru: 'Артикли и род', en: 'Articles and gender' } },
  { slug: 'de.word-order', languageCode: 'de', sortOrder: 30,
    titles: { ru: 'Порядок слов', en: 'Word order' } },
  { slug: 'de.verb-tenses', languageCode: 'de', sortOrder: 40,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'de.separable-verbs', languageCode: 'de', sortOrder: 50,
    titles: { ru: 'Отделяемые приставки', en: 'Separable verbs' } },
  { slug: 'de.spelling', languageCode: 'de', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'de.vocabulary-choice', languageCode: 'de', sortOrder: 70,
    titles: { ru: 'Выбор слова', en: 'Vocabulary choice' } },
  { slug: 'de.other', languageCode: 'de', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'es.prepositions', languageCode: 'es', sortOrder: 10,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'es.ser-vs-estar', languageCode: 'es', sortOrder: 20,
    titles: { ru: 'Ser и estar', en: 'Ser vs estar' } },
  { slug: 'es.verb-tenses', languageCode: 'es', sortOrder: 30,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'es.subjunctive', languageCode: 'es', sortOrder: 40,
    titles: { ru: 'Сослагательное наклонение', en: 'Subjunctive' } },
  { slug: 'es.articles-and-gender', languageCode: 'es', sortOrder: 50,
    titles: { ru: 'Артикли и род', en: 'Articles and gender' } },
  { slug: 'es.spelling', languageCode: 'es', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'es.vocabulary-choice', languageCode: 'es', sortOrder: 70,
    titles: { ru: 'Выбор слова', en: 'Vocabulary choice' } },
  { slug: 'es.other', languageCode: 'es', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'fr.articles-and-gender', languageCode: 'fr', sortOrder: 10,
    titles: { ru: 'Артикли и род существительных', en: 'Articles and noun gender' } },
  { slug: 'fr.prepositions', languageCode: 'fr', sortOrder: 20,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'fr.verb-tenses', languageCode: 'fr', sortOrder: 30,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'fr.être-vs-avoir-auxiliary', languageCode: 'fr', sortOrder: 40,
    titles: { ru: 'Вспомогательные глаголы être/avoir', en: 'Être vs avoir as auxiliary' } },
  { slug: 'fr.adjective-agreement', languageCode: 'fr', sortOrder: 50,
    titles: { ru: 'Согласование прилагательных', en: 'Adjective agreement' } },
  { slug: 'fr.negation', languageCode: 'fr', sortOrder: 60,
    titles: { ru: 'Отрицание (ne...pas)', en: 'Negation (ne...pas)' } },
  { slug: 'fr.spelling', languageCode: 'fr', sortOrder: 70,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'fr.other', languageCode: 'fr', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'it.articles-and-gender', languageCode: 'it', sortOrder: 10,
    titles: { ru: 'Артикли и род существительных', en: 'Articles and noun gender' } },
  { slug: 'it.prepositions', languageCode: 'it', sortOrder: 20,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'it.verb-tenses', languageCode: 'it', sortOrder: 30,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'it.essere-vs-avere-auxiliary', languageCode: 'it', sortOrder: 40,
    titles: { ru: 'Вспомогательные глаголы essere/avere', en: 'Essere vs avere as auxiliary' } },
  { slug: 'it.adjective-agreement', languageCode: 'it', sortOrder: 50,
    titles: { ru: 'Согласование прилагательных', en: 'Adjective agreement' } },
  { slug: 'it.spelling', languageCode: 'it', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'it.other', languageCode: 'it', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'pt.articles-and-gender', languageCode: 'pt', sortOrder: 10,
    titles: { ru: 'Артикли и род существительных', en: 'Articles and noun gender' } },
  { slug: 'pt.ser-vs-estar', languageCode: 'pt', sortOrder: 20,
    titles: { ru: 'Ser и estar', en: 'Ser vs estar' } },
  { slug: 'pt.prepositions', languageCode: 'pt', sortOrder: 30,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'pt.verb-tenses', languageCode: 'pt', sortOrder: 40,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'pt.subjunctive', languageCode: 'pt', sortOrder: 50,
    titles: { ru: 'Сослагательное наклонение', en: 'Subjunctive' } },
  { slug: 'pt.spelling', languageCode: 'pt', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'pt.other', languageCode: 'pt', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'nl.articles-and-gender', languageCode: 'nl', sortOrder: 10,
    titles: { ru: 'Артикли (de/het) и род', en: 'Articles (de/het) and gender' } },
  { slug: 'nl.word-order', languageCode: 'nl', sortOrder: 20,
    titles: { ru: 'Порядок слов', en: 'Word order' } },
  { slug: 'nl.separable-verbs', languageCode: 'nl', sortOrder: 30,
    titles: { ru: 'Отделяемые приставки', en: 'Separable verbs' } },
  { slug: 'nl.prepositions', languageCode: 'nl', sortOrder: 40,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'nl.verb-tenses', languageCode: 'nl', sortOrder: 50,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'nl.spelling', languageCode: 'nl', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'nl.other', languageCode: 'nl', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'pl.case-declension', languageCode: 'pl', sortOrder: 10,
    titles: { ru: 'Склонение по падежам', en: 'Case declension' } },
  { slug: 'pl.verb-aspect', languageCode: 'pl', sortOrder: 20,
    titles: { ru: 'Глагольный вид (совершенный/несовершенный)', en: 'Verbal aspect (perfective/imperfective)' } },
  { slug: 'pl.prepositions', languageCode: 'pl', sortOrder: 30,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'pl.gender-agreement', languageCode: 'pl', sortOrder: 40,
    titles: { ru: 'Согласование по роду', en: 'Gender agreement' } },
  { slug: 'pl.numerals', languageCode: 'pl', sortOrder: 50,
    titles: { ru: 'Числительные', en: 'Numerals' } },
  { slug: 'pl.spelling', languageCode: 'pl', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'pl.other', languageCode: 'pl', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'cz.case-declension', languageCode: 'cz', sortOrder: 10,
    titles: { ru: 'Склонение по падежам', en: 'Case declension' } },
  { slug: 'cz.verb-aspect', languageCode: 'cz', sortOrder: 20,
    titles: { ru: 'Глагольный вид (совершенный/несовершенный)', en: 'Verbal aspect (perfective/imperfective)' } },
  { slug: 'cz.prepositions', languageCode: 'cz', sortOrder: 30,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'cz.gender-agreement', languageCode: 'cz', sortOrder: 40,
    titles: { ru: 'Согласование по роду', en: 'Gender agreement' } },
  { slug: 'cz.spelling', languageCode: 'cz', sortOrder: 50,
    titles: { ru: 'Орфография (i/y, diakritika)', en: 'Spelling (i/y, diacritics)' } },
  { slug: 'cz.other', languageCode: 'cz', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'sk.case-declension', languageCode: 'sk', sortOrder: 10,
    titles: { ru: 'Склонение по падежам', en: 'Case declension' } },
  { slug: 'sk.verb-aspect', languageCode: 'sk', sortOrder: 20,
    titles: { ru: 'Глагольный вид (совершенный/несовершенный)', en: 'Verbal aspect (perfective/imperfective)' } },
  { slug: 'sk.prepositions', languageCode: 'sk', sortOrder: 30,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'sk.gender-agreement', languageCode: 'sk', sortOrder: 40,
    titles: { ru: 'Согласование по роду', en: 'Gender agreement' } },
  { slug: 'sk.spelling', languageCode: 'sk', sortOrder: 50,
    titles: { ru: 'Орфография (i/y, dĺžeň)', en: 'Spelling (i/y, vowel length)' } },
  { slug: 'sk.other', languageCode: 'sk', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'dk.word-order', languageCode: 'dk', sortOrder: 10,
    titles: { ru: 'Порядок слов (V2)', en: 'Word order (V2 rule)' } },
  { slug: 'dk.common-vs-neuter-gender', languageCode: 'dk', sortOrder: 20,
    titles: { ru: 'Общий и средний род (en/et)', en: 'Common vs neuter gender (en/et)' } },
  { slug: 'dk.prepositions', languageCode: 'dk', sortOrder: 30,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'dk.verb-tenses', languageCode: 'dk', sortOrder: 40,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'dk.definite-suffix', languageCode: 'dk', sortOrder: 50,
    titles: { ru: 'Определённый артикль-суффикс', en: 'Definite article suffix' } },
  { slug: 'dk.spelling', languageCode: 'dk', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'dk.other', languageCode: 'dk', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'no.word-order', languageCode: 'no', sortOrder: 10,
    titles: { ru: 'Порядок слов (V2)', en: 'Word order (V2 rule)' } },
  { slug: 'no.common-vs-neuter-gender', languageCode: 'no', sortOrder: 20,
    titles: { ru: 'Общий и средний род (en/et)', en: 'Common vs neuter gender (en/et)' } },
  { slug: 'no.prepositions', languageCode: 'no', sortOrder: 30,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'no.verb-tenses', languageCode: 'no', sortOrder: 40,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'no.definite-suffix', languageCode: 'no', sortOrder: 50,
    titles: { ru: 'Определённый артикль-суффикс', en: 'Definite article suffix' } },
  { slug: 'no.spelling', languageCode: 'no', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'no.other', languageCode: 'no', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'se.word-order', languageCode: 'se', sortOrder: 10,
    titles: { ru: 'Порядок слов (V2)', en: 'Word order (V2 rule)' } },
  { slug: 'se.common-vs-neuter-gender', languageCode: 'se', sortOrder: 20,
    titles: { ru: 'Общий и средний род (en/ett)', en: 'Common vs neuter gender (en/ett)' } },
  { slug: 'se.prepositions', languageCode: 'se', sortOrder: 30,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'se.verb-tenses', languageCode: 'se', sortOrder: 40,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'se.definite-suffix', languageCode: 'se', sortOrder: 50,
    titles: { ru: 'Определённый артикль-суффикс', en: 'Definite article suffix' } },
  { slug: 'se.spelling', languageCode: 'se', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'se.other', languageCode: 'se', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'fi.case-declension', languageCode: 'fi', sortOrder: 10,
    titles: { ru: 'Падежи (местные и др.)', en: 'Case declension (locatives and others)' } },
  { slug: 'fi.consonant-gradation', languageCode: 'fi', sortOrder: 20,
    titles: { ru: 'Чередование ступеней согласных', en: 'Consonant gradation' } },
  { slug: 'fi.partitive-vs-nominative', languageCode: 'fi', sortOrder: 30,
    titles: { ru: 'Партитив и номинатив', en: 'Partitive vs nominative' } },
  { slug: 'fi.verb-types', languageCode: 'fi', sortOrder: 40,
    titles: { ru: 'Типы спряжения глаголов', en: 'Verb conjugation types' } },
  { slug: 'fi.possessive-suffixes', languageCode: 'fi', sortOrder: 50,
    titles: { ru: 'Притяжательные суффиксы', en: 'Possessive suffixes' } },
  { slug: 'fi.spelling', languageCode: 'fi', sortOrder: 60,
    titles: { ru: 'Орфография (долгота гласных/согласных)', en: 'Spelling (vowel/consonant length)' } },
  { slug: 'fi.other', languageCode: 'fi', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'gr.case-declension', languageCode: 'gr', sortOrder: 10,
    titles: { ru: 'Склонение по падежам', en: 'Case declension' } },
  { slug: 'gr.articles-and-gender', languageCode: 'gr', sortOrder: 20,
    titles: { ru: 'Артикли и род существительных', en: 'Articles and noun gender' } },
  { slug: 'gr.verb-aspect', languageCode: 'gr', sortOrder: 30,
    titles: { ru: 'Глагольный вид', en: 'Verbal aspect' } },
  { slug: 'gr.prepositions', languageCode: 'gr', sortOrder: 40,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'gr.word-order', languageCode: 'gr', sortOrder: 50,
    titles: { ru: 'Порядок слов', en: 'Word order' } },
  { slug: 'gr.spelling', languageCode: 'gr', sortOrder: 60,
    titles: { ru: 'Орфография (ударение, омофоны)', en: 'Spelling (accentuation, homophones)' } },
  { slug: 'gr.other', languageCode: 'gr', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'tr.vowel-harmony', languageCode: 'tr', sortOrder: 10,
    titles: { ru: 'Гармония гласных', en: 'Vowel harmony' } },
  { slug: 'tr.case-suffixes', languageCode: 'tr', sortOrder: 20,
    titles: { ru: 'Падежные суффиксы', en: 'Case suffixes' } },
  { slug: 'tr.possessive-suffixes', languageCode: 'tr', sortOrder: 30,
    titles: { ru: 'Притяжательные суффиксы', en: 'Possessive suffixes' } },
  { slug: 'tr.verb-tenses', languageCode: 'tr', sortOrder: 40,
    titles: { ru: 'Времена глагола', en: 'Verb tenses' } },
  { slug: 'tr.word-order', languageCode: 'tr', sortOrder: 50,
    titles: { ru: 'Порядок слов (SOV)', en: 'Word order (SOV)' } },
  { slug: 'tr.spelling', languageCode: 'tr', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'tr.other', languageCode: 'tr', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'cn.tones', languageCode: 'cn', sortOrder: 10,
    titles: { ru: 'Тоны', en: 'Tones' } },
  { slug: 'cn.measure-words', languageCode: 'cn', sortOrder: 20,
    titles: { ru: 'Счётные слова', en: 'Measure words (classifiers)' } },
  { slug: 'cn.word-order', languageCode: 'cn', sortOrder: 30,
    titles: { ru: 'Порядок слов', en: 'Word order' } },
  { slug: 'cn.aspect-particles', languageCode: 'cn', sortOrder: 40,
    titles: { ru: 'Видовые частицы (了, 过, 着)', en: 'Aspect particles (了, 过, 着)' } },
  { slug: 'cn.le-particle-usage', languageCode: 'cn', sortOrder: 50,
    titles: { ru: 'Употребление частицы 了', en: 'Usage of the particle 了' } },
  { slug: 'cn.vocabulary-choice', languageCode: 'cn', sortOrder: 60,
    titles: { ru: 'Выбор слова', en: 'Vocabulary choice' } },
  { slug: 'cn.other', languageCode: 'cn', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'jp.particles', languageCode: 'jp', sortOrder: 10,
    titles: { ru: 'Частицы (は/が/を/に)', en: 'Particles (wa/ga/o/ni)' } },
  { slug: 'jp.verb-conjugation', languageCode: 'jp', sortOrder: 20,
    titles: { ru: 'Спряжение глаголов', en: 'Verb conjugation' } },
  { slug: 'jp.keigo-politeness', languageCode: 'jp', sortOrder: 30,
    titles: { ru: 'Уровни вежливости (кэйго)', en: 'Politeness levels (keigo)' } },
  { slug: 'jp.counters', languageCode: 'jp', sortOrder: 40,
    titles: { ru: 'Счётные суффиксы', en: 'Counters' } },
  { slug: 'jp.word-order', languageCode: 'jp', sortOrder: 50,
    titles: { ru: 'Порядок слов (SOV)', en: 'Word order (SOV)' } },
  { slug: 'jp.vocabulary-choice', languageCode: 'jp', sortOrder: 60,
    titles: { ru: 'Выбор слова', en: 'Vocabulary choice' } },
  { slug: 'jp.other', languageCode: 'jp', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },

  { slug: 'ru.case-declension', languageCode: 'ru', sortOrder: 10,
    titles: { ru: 'Склонение по падежам', en: 'Case declension' } },
  { slug: 'ru.verb-aspect', languageCode: 'ru', sortOrder: 20,
    titles: { ru: 'Глагольный вид (совершенный/несовершенный)', en: 'Verbal aspect (perfective/imperfective)' } },
  { slug: 'ru.verbs-of-motion', languageCode: 'ru', sortOrder: 30,
    titles: { ru: 'Глаголы движения', en: 'Verbs of motion' } },
  { slug: 'ru.gender-agreement', languageCode: 'ru', sortOrder: 40,
    titles: { ru: 'Согласование по роду', en: 'Gender agreement' } },
  { slug: 'ru.prepositions', languageCode: 'ru', sortOrder: 50,
    titles: { ru: 'Предлоги', en: 'Prepositions' } },
  { slug: 'ru.spelling', languageCode: 'ru', sortOrder: 60,
    titles: { ru: 'Орфография', en: 'Spelling' } },
  { slug: 'ru.other', languageCode: 'ru', sortOrder: 999,
    titles: { ru: 'Прочее', en: 'Other' } },
];

export async function seedGrammarTopics(prisma: PrismaClient): Promise<number> {
  for (const topic of GRAMMAR_TOPICS) {
    await prisma.grammarTopic.upsert({
      where: { slug: topic.slug },
      update: { languageCode: topic.languageCode, titles: topic.titles, sortOrder: topic.sortOrder },
      create: topic,
    });
  }
  return GRAMMAR_TOPICS.length;
}

if (require.main === module) {
  const prisma = new PrismaClient();
  seedGrammarTopics(prisma)
    .then((count) => {
      // eslint-disable-next-line no-console
      console.log(`Seeded ${count} grammar topics`);
    })
    .catch((error) => {
      // eslint-disable-next-line no-console
      console.error('Grammar topic seed failed:', error);
      process.exitCode = 1;
    })
    .finally(() => prisma.$disconnect());
}
